mappings:
  - api_endpoint: /users
    query: SELECT id, name, email, created_at FROM users ORDER BY id;
    columns:
      id: user_id
      name: full_name
      email: email
      created_at: created_at

  - api_endpoint: /orders
    query: >
      SELECT o.id, u.name, o.product, o.total, o.created_at
      FROM orders o JOIN users u ON u.id = o.user_id
      ORDER BY o.id;
    columns:
      id: order_id
      name: user_name
      product: product
      total: total
      created_at: created_at
  - api_endpoint: /hello
    query: SELECT now() AS server_time;

