apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: acl-api
spec:
  type: ClusterIP
  selector:
    app: acl-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
